#!/usr/bin/env bash

GNOSTR_RELAYER=${GNOSTR_RELAYER:-gnostr-cat}

if ! command -v $GNOSTR_RELAYER >&2 >/dev/null; then
	printf "error: gnostr relayer '%s' not found, set \$GNOSTR_RELAYER or install '%s'\n" $GNOSTR_RELAYER $GNOSTR_RELAYER
	exit 1
fi

usage() {
	printf "usage: gnostr send [OPTIONS...] <commit> [GNOSTR OPTIONS...]\n\n"

	printf "OPTIONS\n\n"
	printf "     -r            Relay to broadcast to. Will use 'git config gnostr.relays' by default\n"
	printf "     -d            Dry run. Just print event to stdout instead of relaying.\n"
	printf "\n"
	printf "     any other gnostr option is supported here:\n\n"
	printf "GNOSTR OPTIONS\n"
	gnostr | sed '1,/OPTIONS/d'
	printf "\nEXAMPLES\n\n"
	printf "gnostr-send -d HEAD^- -t gnostr -t gnostr_dev --pow 15\n\n"
	exit 0
}

while getopts "dr:t:" o; do
    case "${o}" in
        r)
            relay=${OPTARG}
            ;;
        t)
            tag=${OPTARG}
            ;;
        d)
            dryrun=1
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))


if [ -z $relay ]; then
	relay=$(git config gnostr.relays)
	if [[ $relay == "" ]]; then
		unset relay
	fi
fi

if [ -z $1 ]; then
	usage
	exit 0
fi

commit=$1
shift

# this can be overridden
sec="$(gnostr-git config gnostr.secretkey)"
if [[ $sec != "" ]]; then
	sec="--sec $sec"
fi

patch="$(gnostr-git format-patch --stdout $commit)"
subject=$(<<<"$patch" grep "^Subject:"| head -n1 | sed 's,^Subject: ,,')
author=$(<<<"$patch" grep "^From:"| head -n1 | sed 's,^From: ,,')
json=$(gnostr --envelope $sec --kind 19691228 --tag author "$author" --tag subject "$subject" --content "$patch" "$@")

id=$(jq -r '.[1].id' <<<"$json")

if [ -n "$dryrun" ]; then
	echo "$json"
	printf "\nDRY RUN. printing event data\n" >&2
elif [ -z "$relay" ]; then
	echo "$json"
	printf "\nRELAY NOT SET, not relaying. Use -r wss://relay.damus.io or 'git config --global gnostr.relays wss://relay.damus.io'\n" >&2
else
	echo "$id"
	printf "relaying to $relay using $NOSTR_RELAYER...\n" >&2
	<<<$json $NOSTR_RELAYER "$relay"
fi

if [[ $sec == "" ]]; then
	printf "NOSTR SECRET KEY NOT SET, using random key. Use --sec <key> or 'git config --global gnostr.secretkey <hexkey>'\n" >&2
fi
