#!/usr/bin/env bash
gnostr --sec $(gnostr --hash) --tag banner https://pbs.twimg.com/profile_banners/15942578/1686574351/600x200 --tag picture https://pbs.twimg.com/profile_images/1625667085849313280/XaB2RaMk_400x400.jpg --tag lud16 randymcmillan@current.tips --tag display_name @RandyMcMillan --tag about "fuzzy logician - designing human friendly systems" --tag name randymcmillan --envelope --content "" | gnostr-cat -u wss:nos.lol

#gnostr-query -i $(gnostr-nip0  | jq .[1] | tr -d "\"" ) | gnostr-cat -u wss://nos.lol