#!/usr/bin/env bash

## We try a local node first
## then mempool.space
## then blochchain.info
## finally docs-demo.btc.quiknode.pro

declare -a BLOCKHEIGHT
function gnostr_blockheight(){
	
	type -P bitcoin-cli >/tmp/gnostr.log && \
	BLOCKHEIGHT=$(bitcoin-cli getblockcount 2>/tmp/gnostr.log) >/tmp/gnostr.log || \
	BLOCKHEIGHT=$(curl -s "https://mempool.space/api/blocks/tip/height") || \
	BLOCKHEIGHT=$(curl -s https://blockchain.info/q/getblockcount 2>/dev/null) || \
	BLOCKHEIGHT=$(curl -s https://docs-demo.btc.quiknode.pro/   -X POST   -H "Content-Type: application/json"   --data '{ "method": "getblockcount" }' 2>/tmp/gnostr.log | jq --arg v "$result" '.result')
	echo $BLOCKHEIGHT
	#return $BLOCKHEIGHT

}
gnostr_blockheight
cat /tmp/gnostr.log