env:  # Global defaults
  PACKAGE_MANAGER_INSTALL: "apt-get update && apt-get install -y"
  MAKEJOBS: "-j10"
  TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
  CI_FAILFAST_TEST_LEAVE_DANGLING: "1"  # Cirrus CI does not care about dangling process and setting this variable avoids killing the CI script itself on error
  CCACHE_SIZE: "200M"
  CCACHE_DIR: "/tmp/ccache_dir"
  CCACHE_NOHASHDIR: "1"  # Debug info might contain a stale path if the build dir changes, but this is fine

cirrus_ephemeral_worker_template_env: &CIRRUS_EPHEMERAL_WORKER_TEMPLATE_ENV
  DANGER_RUN_CI_ON_HOST: "1"  # Containers will be discarded after the run, so there is no risk that the ci scripts modify the system

persistent_worker_template_env: &PERSISTENT_WORKER_TEMPLATE_ENV
  RESTART_CI_DOCKER_BEFORE_RUN: "1"

persistent_worker_template: &PERSISTENT_WORKER_TEMPLATE
  persistent_worker: {}  # https://cirrus-ci.org/guide/persistent-workers/

# https://cirrus-ci.org/guide/tips-and-tricks/#sharing-configuration-between-tasks
filter_template: &FILTER_TEMPLATE
  skip: $CIRRUS_REPO_FULL_NAME == "bitcoin-core/gui" && $CIRRUS_PR == ""  # No need to run on the read-only mirror, unless it is a PR. https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution
  stateful: false  # https://cirrus-ci.org/guide/writing-tasks/#stateful-tasks

base_template: &BASE_TEMPLATE
  << : *FILTER_TEMPLATE
  merge_base_script:
    # Unconditionally install git (used in fingerprint_script) and set the
    # default git author name (used in verify-commits.py)
    - bash -c "$PACKAGE_MANAGER_INSTALL git"
    - git config --global user.email "ci@ci.ci"
    - git config --global user.name "ci"
    - if [ "$CIRRUS_PR" = "" ]; then exit 0; fi
    - git fetch $CIRRUS_REPO_CLONE_URL $CIRRUS_BASE_BRANCH
    - git merge FETCH_HEAD  # Merge base to detect silent merge conflicts

main_template: &MAIN_TEMPLATE
  timeout_in: 120m  # https://cirrus-ci.org/faq/#instance-timed-out
  ccache_cache:
    folder: "/tmp/ccache_dir"
  ci_script:
    - ./ci/test_run_all.sh

global_task_template: &GLOBAL_TASK_TEMPLATE
  << : *BASE_TEMPLATE
  container:
    # https://cirrus-ci.org/faq/#are-there-any-limits
    # Each project has 16 CPU in total, assign 2 to each container, so that 8 tasks run in parallel
    cpu: 2
    greedy: true
    memory: 8G  # Set to 8GB to avoid OOM. https://cirrus-ci.org/guide/linux/#linux-containers
  depends_built_cache:
    folder: "depends/built"
    fingerprint_script: echo $CIRRUS_TASK_NAME $(git rev-list -1 HEAD ./depends)
  << : *MAIN_TEMPLATE

macos_native_task_template: &MACOS_NATIVE_TASK_TEMPLATE
  << : *BASE_TEMPLATE
  check_clang_script:
    - clang --version
  brew_install_script:
    - brew install boost libevent qt@5 miniupnpc libnatpmp ccache zeromq qrencode libtool automake gnu-getopt
  << : *MAIN_TEMPLATE

compute_credits_template: &CREDITS_TEMPLATE
  # https://cirrus-ci.org/pricing/#compute-credits
  # Only use credits for pull requests to the main repo
  use_compute_credits: $CIRRUS_REPO_FULL_NAME == 'bitcoin/bitcoin' && $CIRRUS_PR != ""

task:
  name: '[CMake, no depends, BUILD_GUI=OFF] [bionic]'
  << : *BASE_TEMPLATE
  container:
    image: ubuntu:bionic
    cpu: 4
    memory: 16G
  ccache_cache:
    folder: "/tmp/ccache_dir"
  env:
    << : *CIRRUS_EPHEMERAL_WORKER_TEMPLATE_ENV
  install_script:
    - apt-get update
    - apt-get install -y --no-install-recommends --no-upgrade g++-8 build-essential pkg-config ccache python3 cmake libevent-dev libboost-dev libsqlite3-dev libminiupnpc-dev libnatpmp-dev libzmq3-dev systemtap-sdt-dev libdb++-dev
  configure_script:
    - mkdir build
    - cd build
    - CC=gcc-8 CXX=g++-8 cmake -DBUILD_GUI=OFF ..
  build_script:
    - export LC_ALL=C.UTF-8
    - cmake --build build -- -j$(nproc)
  functional_tests_script:
    - export LC_ALL=C.UTF-8
    - ./build/test/functional/test_runner.py --ci -j$(nproc) --tmpdirprefix ${CIRRUS_WORKING_DIR}/test_runner --ansi --combinedlogslen=4000 --timeout-factor=40 --quiet

task:
  name: '[CMake, depends NO_WALLET=1, ENABLE_WALLET=OFF] [bionic]'
  << : *BASE_TEMPLATE
  container:
    image: ubuntu:bionic
    cpu: 4
    memory: 16G
  depends_built_cache:
    folder: "depends/built"
    fingerprint_script: echo $CIRRUS_TASK_NAME $(git rev-list -1 HEAD ./depends)
  ccache_cache:
    folder: "/tmp/ccache_dir"
  env:
    << : *CIRRUS_EPHEMERAL_WORKER_TEMPLATE_ENV
  install_script:
    - apt-get update
    - apt-get install -y --no-install-recommends --no-upgrade g++-8 build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ccache python3 bison cmake
  depends_script:
    - export LC_ALL=C.UTF-8
    - make -C depends -j$(nproc) NO_WALLET=1 LOG=1 CC=gcc-8 CXX=g++-8
    - cat /tmp/cirrus-ci-build/depends/x86_64-pc-linux-gnu/share/toolchain.cmake
  configure_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/cirrus-ci-build/depends/x86_64-pc-linux-gnu/share/toolchain.cmake -DENABLE_WALLET=OFF ..
  build_script:
    - export LC_ALL=C.UTF-8
    - cmake --build build -- -j$(nproc)
  functional_tests_script:
    - export LC_ALL=C.UTF-8
    - ./build/test/functional/test_runner.py --ci -j$(nproc) --tmpdirprefix ${CIRRUS_WORKING_DIR}/test_runner --ansi --combinedlogslen=4000 --timeout-factor=40 --quiet
