#!/bin/bash

#exec $PWD/src/bitcoin-node "$@"
#exec $PWD/src/bitcoin-node -logtimemicros=1 -debug=1 "$@"

OPT=()
OPT+=(-ex "set follow-fork-mode child")
OPT+=(-ex 'define please
    catch syscall lseek
    commands
        bt
    end
    condition $bpnum $rdi == 0
end
please
')
#OPT+=(-ex "catch throw")
#OPT+=(-ex "b kj::Exception::Exception")
#screen -S "bitcoind_${PPID}_$$" -d -m gdb "${OPT[@]}" -ex run --args $PWD/src/bitcoin-node "$@"
#screen -S "bitcoind_${PPID}_$$" env LD_LIBRARY_PATH=$LD_LIBRARY_PATH gdb "${OPT[@]}" -ex run --args $PWD/src/bitcoind "$@"
screen -S "bitcoind_${PPID}_$$" env LD_LIBRARY_PATH=$LD_LIBRARY_PATH gdb "${OPT[@]}" -ex run --args $PWD/src/bitcoin-node "$@"


exit 0


