# ==============================================================================
# configure.ac
# ==============================================================================

# The following line is formatted to be parsed correctly by your autogen.sh
# Syntax: AC_INIT([PackageName], [Version], [BugReportEmail])

AC_INIT([gnostr-notes], [0.1.0], [randymcmillan@gmail.com])

# Specify the directory for auxiliary build tools
AC_CONFIG_AUX_DIR([build-aux])

# Initialize Automake
AM_INIT_AUTOMAKE([-Wall -Werror foreign])

# Check for a C compiler
AC_PROG_CC

# Create the makefile
AC_CONFIG_FILES([Makefile])

# Output the configuration
AC_OUTPUT
