#!/usr/bin/env bash
declare -a LENGTH
declare -a RELAYS
declare -a FULLPATH
declare -a BLOBS
declare -a BLOCKHEIGHT
declare -a TIME
declare -a WEEBLE
declare -a WOBBLE
declare -a REPO_NAME
declare -a CURRENT_BRANCH
REPO_NAME=$(pwd | grep -o "[^/]*$")
CURRENT_BRANCH=$(git branch --show-current)
FULLPATH=$PWD
#source gnostr-nonce
function help(){

  #get_weeble

	printf "WEEBLE=TIME/BLOCKHEIGHT"
  exit;
}

function get_time(){

	TIME=$(date +%s)
	return $TIME

}
get_time

function get_block_height(){
	BLOCKHEIGHT=$(curl https://blockchain.info/q/getblockcount 2>/dev/null || curl -sSL "https://mempool.space/api/blocks/tip/height")
	return $BLOCKHEIGHT
}
get_block_height

function get_weeble(){
	WEEBLE=$(expr $TIME / $BLOCKHEIGHT)
	echo $WEEBLE
}

if [[ $1 == "-h" ]];
then
  help
fi
if [[ $1 == "--help" ]];
then
  help
fi
if [[ $1 == "help" ]];
then
  help
fi
if [[ $1 == "-v" ]];
then
  printf "v0.0.0"; exit
fi
if [[ $1 == "--version" ]];
then
  printf "v0.0.0"; exit
fi
get_weeble
