      - name: Get latest release
        shell: bash
        id: get_latest_release
        run: |
          # Use GitHub API to get the latest release tag
          LATEST_TAG=$(curl -sL https://api.github.com/repos/gnostr-org/gnostr/releases/latest | jq -r ".tag_name")
          echo "Latest release tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Install gnostr (latest release)
        shell: bash
        run: |
          # Construct the installer URL using the latest tag
          INSTALLER_URL="https://github.com/gnostr-org/gnostr/releases/download/${{ steps.get_latest_release.outputs.latest_tag }}/gnostr-installer.sh"
          echo "Installer URL: $INSTALLER_URL"
          curl --proto '=https' --tlsv1.2 -LsSf "$INSTALLER_URL" | sh || \
          cargo-binstall --force --no-confirm gnostr

