.\" Modified from man(1) of FreeBSD, the NetBSD mdoc.template and mdoc.samples
.\" See man mdoc for the short list of editing options
.Dd August 20, 2023     \" DATE
.Dt gnostr 1           \" Program name and manual section number - leave lowercase
.Os Unix-like
.Sh NAME                 \" Section Header - required - don't modify
.Nm gnostr
.\" The following lines are read in generating the apropos database.
.\" Use only key words here as the database is built on these.
.\" Use .Nm macro to designate other names for the documented program.
.Nd a git+nostr command line utiliy.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.sp
.Op Fl -content              \" [-abcd]
<string>                  \" Arguments
    The text contents of the note
.sp
.Op Fl -dm              \" [-abcd]
<hex pubkey>                  \" Arguments
    Create a direct message.
    This will create a `kind 4` note with the contents encrypted
.sp
.Op Fl -envelope              \" [-abcd]
    Wrap the event with `["EVENT", .\&.\&.\& ]` for easy relaying.sp
.sp
.Op Fl -kind              \" [-abcd]
<number>                  \" Arguments
    <number> based on nostr protocol (NIPS)
.sp
.Op Fl -created-at              \" [-abcd]
<unix timestamp>                  \" Arguments
    <unix_timestamp> in seconds.
.sp
.Op Fl -sec              \" [-abcd]
priv_key                  \" Arguments
    a <priv_key> is a sha256 hash
.sp
    try:
        gnostr sha256 <string>
.sp
.Op Fl -pow              \" [-abcd]
<difficulty>                  \" Arguments
.sp
    try:
        gnostr --pow 16
.sp
.Op Fl -mine-pubkey              \" [-abcd]
<difficulty>
.sp
    try:
        gnostr --mine-pubkey --pow 16
.sp
.Op Fl -tag              \" [-abcd]
<key> <value>                  \" Arguments
.sp
    try:
        gnostr --tag pow test --pow 16
.sp
.Op Fl -hash              \" [-abcd]
<value>                  \" Arguments
.sp
.Sh     additonal flags:

.sp
.Op Fl e
<event_id>         \" [-a path]
.sp
.Op Fl p
<pubkey>         \" [-a path]
.sp
.Op Fl t
<hashtag>         \" [-a path]
.sp
.Sh SEE ALSO
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr gnostr-blockheight 1 ,
.Xr gnostr-cat 1 ,
.Xr gnostr-cli 1 ,
.Xr gnostr-client 1 ,
.Xr gnostr-get-relays 1 ,
.Xr gnostr-git 1 ,
.Xr gnostr-git-log 1 ,
.Xr gnostr-git-reflog 1 ,
.Xr gnostr-gnode 1 ,
.Xr gnostr-grep 1 ,
.Xr gnostr-legit 1 ,
.Xr gnostr-nonce 1 ,
.Xr gnostr-post 1 ,
.Xr gnostr-proxy 1 ,
.Xr gnostr-query 1 ,
.Xr gnostr-relays 1 ,
.Xr gnostr-repo 1 ,
.Xr gnostr-req 1 ,
.Xr gnostr-send 1 ,
.Xr gnostr-set-relays 1 ,
.Xr gnostr-sha256 1 ,
.Xr gnostr-tests 1 ,
.Xr gnostr-weeble 1 ,
.Xr gnostr-wobble 1 ...
.sp
.\" .Sh STANDARDS       \" Standards relating to command being described
.\" .Sh HISTORY         \" Document history if command behaves uniquely
.Sh AUTHORS         \" A list of authors of the program
.An John Doe        <nostr id>\" Some author
.An Jane Doe        <nostr id>\" Some other author
.\" .Sh BUGS            \" Document known, unremedied bugs
.sp
