.\" Modified from man(1) of FreeBSD, the NetBSD mdoc.template and mdoc.samples
.\" See man mdoc for the short list of editing options
.Dd August 20, 2023     \" DATE
.Dt gnostr-about 1           \" Program name and manual section number - leave lowercase
.Os Unix-like
.Sh NAME                 \" Section Header - required - don't modify
.Nm gnostr-about
.\" The following lines are read in generating the apropos database.
.\" Use only key words here as the database is built on these.
.\" Use .Nm macro to designate other names for the documented program.
.Nd a git+nostr command line utiliy.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.sp
.Sh SEE ALSO
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr gnostr-blockheight 1 ,
.Xr gnostr-cat 1 ,
.Xr gnostr-cli 1 ,
.Xr gnostr-client 1 ,
.Xr gnostr-get-relays 1 ,
.Xr gnostr-git 1 ,
.Xr gnostr-git-log 1 ,
.Xr gnostr-git-reflog 1 ,
.Xr gnostr-gnode 1 ,
.Xr gnostr-grep 1 ,
.Xr gnostr-legit 1 ,
.Xr gnostr-nonce 1 ,
.Xr gnostr-post 1 ,
.Xr gnostr-proxy 1 ,
.Xr gnostr-query 1 ,
.Xr gnostr-relays 1 ,
.Xr gnostr-repo 1 ,
.Xr gnostr-req 1 ,
.Xr gnostr-send 1 ,
.Xr gnostr-set-relays 1 ,
.Xr gnostr-sha256 1 ,
.Xr gnostr-tests 1 ,
.Xr gnostr-weeble 1 ,
.Xr gnostr-wobble 1 ...
.sp
.\" .Sh STANDARDS       \" Standards relating to command being described
.Sh HISTORY         \" Document history if command behaves uniquely
.Sh ORIGINAL CONTRIBUTORS\" A list of authors of the program
.An @0 <a34b99f22c790c4e36b2b3c2c35a36db06226e41c692fc82b8b56ac1c540c5bd\>
.sp
.An @randymcmillan <edfa27d49d2af37ee331e1225bb6ed1912c6d999281b36d8018ad99bc3573c29\>\" Some other author
.\" .Sh BUGS            \" Document known, unremedied bugs
.sp
