.\" Modified from man(1) of FreeBSD, the NetBSD mdoc.template and mdoc.samples
.\" See man mdoc for the short list of editing options
.Dd August 27, 2023     \" DATE
.Dt gnostr-weeble 1           \" Program name and manual section number
.Os unix-like
.Sh NAME                 \" Section Header - required - don't modify
.Nm gnostr-weeble
.\" The following lines are read in generating the apropos database.
.\" Use only key words here as the database is built on these.
.\" Use .Nm macro to designate other names for the documented program.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm 


.Sh DESCRIPTION          \" Section Header - required - don't modify
.Bl -tag -width "/usr/local/bin/gnostr-weeble        " -compact
        - floor(utc-seconds / blockheight)

          \[lf] utc-seconds / blockheight \[rf]


        - floor(utc-milliseconds / blockheight)

          \[lf] utc-milliseconds / blockheight \[rf]

.El
.Sh FILES

.Bl -tag -width "/usr/local/bin/gnostr-weeble        " -compact
.It Pa /usr/local/bin/gnostr-weeble
bash script
.El                      \" Ends the list
.Sh SEE ALSO

.Xr gnostr-wobble 1 ,

.Xr gnostr-blockheight 1 ,
