name: makefile.yml

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: git fetch
      run: |
          git fetch

    - name: autogen.sh && configure
      run: |
          sudo apt-get install autotools-dev autoconf automake libtool m4
          sudo apt-get install build-essential
          ./autogen.sh && ./configure 

    - name: make bootstrap
      run: |
          make
          make bootstrap

    - name: make brew
      run: |
          make brew
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc

    - name: make template
      run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && make template && checkbrew -h
          make all

    - name: make alpine-build
      run: |
          make alpine-build



