name: makefile.yml

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: git fetch
      run: |
          git fetch

    - name: autogen.sh && configure
      run: |
          sudo apt-get install autotools-dev autoconf automake libtool m4
          sudo apt-get install build-essential
          ./autogen.sh && ./configure 

