name: makefile.yml

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: git fetch
      run: |
          git fetch

    - name: autogen.sh && configure
      run: |
          sudo apt-get install autotools-dev \
          autoconf automake libtool m4 \
          build-essential \
          libssl-dev libcrypto++-dev
    #      ./autogen.sh && ./configure
    - name: make
      run: |
          sudo make
    #- name: make legit
    #  run: |
    #      sudo make legit
    - name: make nostril
      run: |
          sudo make nostril
