version: "3"

services:
  git-server:
    image: rockstorm/git-server
    container_name: git-server
    restart: unless-stopped

    # environment:
      # Password for the git user
      # GIT_PASSWORD: "your-password"

      # Path where the file with the password for the git user will be
      # mounted in the container in order to replace the default one
      # GIT_PASSWORD_FILE: /run/secrets/git_password

      # Setting this variable creates a link in the git user directory
      # to access repositories without absolute paths
      # REPOSITORIES_HOME_LINK: /srv/git

      # Path where the SSH host keys will be mounted in the container
      # in order to replace the default keys
      # SSH_HOST_KEYS_PATH: /tmp/host-keys

      # Set specific UID and GID for the git user
      # GIT_USER_UID: 1001
      # GIT_USER_GID: 1001

    volumes:
      # Folder with git repositories
      - git-repositories:/srv/git

      # File containing the SSH keys of clients that will be allowed
      # to use this service through a public key
      # - /path/to/authorized_keys:/home/git/.ssh/authorized_keys

      # A folder with host SSH keys to use instead of the default ones
      # - /path/to/host-keys:/tmp/host-keys:ro

      # Configuration file for the OpenSSH daemon to use instead of
      # the one that is generated by default
      # - ./sshd_config.sample:/etc/ssh/sshd_config:ro

      # File containing the password for the git user
      # - /path/to/password/file:/run/secrets/git_password:ro

      # Disable interactive SSH login for the git user
      # - /executable/file:/home/git/git-shell-commands/no-interactive-login

    ports:
      - "2222:22"

volumes:
  git-repositories:

# Use Docker secrets to provide the git password file instead of mounting
#     secrets:
#       - git_password
#
# secrets:
#   git_password:
#     file: /path/to/password/file
