name: make bitcoin-guix-sigs

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.6.0
      with:
          ssh-private-key: ${{ secrets.OPENSSH_PRIVATE_KEY }}

    - name: git fetch
      run: |
          git fetch

    - name: make bitcoin-guix-sigs
      run: |
          make bitcoin-guix-sigs



