# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu-latest-bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        run: echo y | ./boot-strap.sh


  macos-10-15-bootstrap:
     runs-on: macos-10.15
     steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        run: echo y | ./boot-strap.sh

  macos-11-4-bootstrap:
     runs-on: macos-11.4
     steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        run: echo y | ./boot-strap.sh

  macos-latest-bootstrap:
     runs-on: macos-latest
     steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        run: echo y | ./boot-strap.sh

  ubuntu-latest-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make

  macos-10-15-make:
     runs-on: macos-10.15
     steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make

  macos-11-4-make:
     runs-on: macos-11.4
     steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make

  macos-latest-make:
     runs-on: macos-latest
     steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make

  macos-latest-install-alpine-shell:
     runs-on: macos-latest
     steps:
      - uses: actions/checkout@v2
      - name: install-alpine-shell
        run: |
          ./install-alpine-shell.sh

