# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu-bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        run: ./boot-strap.sh


  macos-10-15-bootstrap:
     runs-on: macos-10.15
     steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        run: ./boot-strap.sh

  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make


  build4:
     runs-on: macos-10.15
     steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make
