name: macos-make-legit

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-legit:
    strategy:
      matrix:
        os: [macos-latest, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '3'
      - name: install rustup unattended
        run: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: brew install libtool autoconf automake
        run: |
            brew install libtool autoconf automake
      - name: make
        run: |
            printenv
            make
      - name: make legit
        run: |
            make submodules legit
