name: make nvm

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      if: ${{ ! env.ACT }}
      with:
        fetch-depth: 0
    - name: make nvm
      run: |
          #sudo apt update && sudo apt upgrade -y
          #sudo apt install --fix-missing  build-essential automake
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /root/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc act make
          #curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          #wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /root/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          make

