name: makefile.yml

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install cargo-binstall
      id: binstall
      continue-on-error: true
      uses: cargo-bins/cargo-binstall@v1.18.1
    - name: Install gnostr (latest release)
      uses: ./.github/actions/get-latest
      #if: runner.os != 'macOS'

    - name: make-commands
      run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install --fix-missing automake bash g++ pkg-config -y
          ./autogen.sh env
          make
