name: make nvm

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      if: ${{ ! env.ACT }}
      with:
        fetch-depth: 0
    - name: brew install
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: linuxbrew (with retries)
      run: |
        test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
        test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc
      if: matrix.os == 'ubuntu-latest'
    - name: Install gnostr via cargo-binstall
      uses: ./.github/actions/cargo-binstall-gnostr
    - name: make nvm
      run: |
          make nvm
