name: make nvm

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      if: ${{ ! env.ACT }}
      with:
        fetch-depth: '3'
    - name: make nvm
      run: |
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /root/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt update && sudo apt upgrade -y
          sudo apt install --fix-missing  build-essential make
          brew install gcc
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          $(which make) -f GNUmakefile nvm && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
                                            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && \
                                            nvm install 10 && \
                                            nvm install 11 && \
                                            nvm install 12 && \
                                            nvm install 13 && \
                                            nvm install 14 && \
                                            nvm install 15 && \
                                            nvm install 16 && \
                                            nvm install 17 && \
                                            nvm install 18

