name: make nvm

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: git fetch
      run: |
          git fetch

    - name: make bootstrap
      run: |
          make
          make bootstrap

    - name: make brew
      run: |
          make brew
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc

    - name: make nvm
      run: |
          make nvm && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
                                            nvm install 10
