name: makefile.yml

on:
  push:
    branches: [ "master", "main" , "**", "**/**" ]
  pull_request:
    branches: [ "master", "main" , "**", "**/**" ]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: make-commands
      run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install --fix-missing automake bash g++ pkg-config -y
          ./autogen.sh env
          make
