name: Sync Docker Hub README

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/sync-readme.yml

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: 'rockstorm'
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: rockstorm/git-server