name: Test Docker Build

on:
  schedule:
    - cron: '20 7 * * 4'
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [master, docker]
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ matrix.branch }}

    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
